YUPZ/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from orders.views import stripe_webhook_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('products/', include('products.urls', namespace='products')),
    path('vacancies/', include('vacancy.urls', namespace='vacancy')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                             document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import OrderCreateView, SuccessTemplateView, CanceledTemplateView, OrderDetailView

app_name = 'orders'

urlpatterns = [
    path('order/', OrderCreateView.as_view(), name='order_create'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order_list'),
    path('order-success/', SuccessTemplateView.as_view(), name='order_success'),
    path('order-canceled/', CanceledTemplateView.as_view(), name='order_canceled'),
]

products/urls.py
from django.urls import path
from .views import ProductsView, ProductDetailView, BasketView, AddToBasketView, RemoveFromBasketView, UpdateBasketView

app_name = 'products'

urlpatterns = [
    path('', ProductsView.as_view(), name='products'),
    path('basket/', BasketView.as_view(), name='basket'),
    path('basket/update/<slug:slug>/', UpdateBasketView.as_view(), name='update_basket'),
    path("basket/remove/<slug:product_slug>/", RemoveFromBasketView.as_view(), name="remove_from_basket"),
    path('products/<slug:product_slug>/add/', AddToBasketView.as_view(), name='add_to_basket'),
    path('<slug:product_slug>/', ProductDetailView.as_view(), name='product_detail'),

]

users/urls.py
from django.urls import path
from .views import (LoginView, RegisterView, ProfileView, CustomLogoutView, CustomPasswordResetView,
                    CustomPasswordResetConfirmView)
from django.contrib.auth import views as auth_views


app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
    # другие маршруты
]

orders/models.py
from django.db import models
from users.models import User
from products.models import Basket


class Order(models.Model):
    CREATED = 0
    CONFIRMED = 1
    PLANNING = 2
    IN_PRODUCTION = 3
    QUALITY_CONTROL = 4
    READY_FOR_SHIPMENT = 5
    SENT_TO_DELIVERY = 6
    DELIVERED = 7
    COMPLETED = 8
    CANCELLED = 9

    STATUS_CHOICES = [
        (CREATED, 'Новый'),
        (CONFIRMED, 'Подтверждён'),
        (PLANNING, 'В планировании'),
        (IN_PRODUCTION, 'В производстве'),
        (QUALITY_CONTROL, 'Контроль качества (ОТК)'),
        (READY_FOR_SHIPMENT, 'Готов к отгрузке'),
        (SENT_TO_DELIVERY, 'Передан в доставку'),
        (DELIVERED, 'Доставлен'),
        (COMPLETED, 'Завершён'),
        (CANCELLED, 'Отменён'),
    ]

    first_name = models.CharField(max_length=150, verbose_name='Имя')
    last_name = models.CharField(max_length=150, verbose_name='Фамилия')
    email = models.EmailField(max_length=256, verbose_name='Почта')
    phone_number = models.CharField(max_length=50, verbose_name='Номер телефона')
    address = models.CharField(max_length=256, verbose_name='Адрес доставки')
    basket_history = models.JSONField(default=dict, verbose_name='История корзины')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='Пользователь')
    rejection_reason = models.TextField(blank=True, null=True, verbose_name="Причина отказа")
    status = models.SmallIntegerField(default=CREATED, choices=STATUS_CHOICES, verbose_name='Статус')

    def __str__(self):
        return f'Заказ {self.id} {self.first_name} {self.last_name}'

    def update_after_payment(self):
        baskets = Basket.objects.filter(user=self.initiator)
        self.status = self.CONFIRMED
        self.basket_history = {
            'purchased_items': [basket.de_json() for basket in baskets],
            'total_sum': float(Basket.total_sum(self.initiator)),
        }
        baskets.delete()
        self.save()


orders/forms.py
from django import forms
from orders.models import Order
from django.core.validators import RegexValidator

cyrillic_validator = RegexValidator(
    regex=r'^[А-Яа-яЁё\s\-]+$',
    message='Разрешены только кириллические буквы, пробелы и тире.'
)

address_validator = RegexValidator(
    regex=r'^[А-Яа-яЁё0-9\s\-\.,]+$',
    message='Разрешены только кириллические буквы, пробелы и тире.'
)


class OrderForm(forms.ModelForm):
    first_name = forms.CharField(
        validators=[cyrillic_validator],
        widget=forms.TextInput(attrs={'class': 'order-form__input', 'placeholder': 'Введите ваше Имя'})
    )
    last_name = forms.CharField(
        validators=[cyrillic_validator],
        widget=forms.TextInput(attrs={'class': 'order-form__input', 'placeholder': 'Введите вашу Фамилию'})
    )
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'order-form__input', 'placeholder': 'Введите адрес электронной почты', 'autocomplete': 'email'
    }))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'order-form__input', 'placeholder': 'Введите ваш номер'
    }))
    address = forms.CharField(
        validators=[address_validator],
        widget=forms.TextInput(attrs={'class': 'order-form__input', 'placeholder': 'Введите адрес доставки'})
    )

    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'address']

orders/views.py
import stripe
from django.http import JsonResponse
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.base import TemplateView
from .forms import OrderForm
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from products.models import Basket
from orders.models import Order
from django.contrib.auth.mixins import LoginRequiredMixin

stripe.api_key = settings.STRIPE_SECRET_KEY


class SuccessTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'orders/order-success.html'


class CanceledTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'orders/order-cancel.html'


class OrderDetailView(LoginRequiredMixin, DetailView):
    template_name = 'orders/order_detail.html'
    model = Order
    context_object_name = "order"

    def get_object(self, queryset=None):
        return get_object_or_404(Order, pk=self.kwargs.get("pk"))


class OrderCreateView(LoginRequiredMixin, CreateView):
    form_class = OrderForm
    template_name = 'orders/order_form.html'

    def form_valid(self, form):
        order = form.save(commit=False)
        order.initiator = self.request.user
        order.save()
        self.object = order
        baskets = Basket.objects.filter(user=self.request.user)
        line_items = []
        for basket in baskets:
            item = {
                'price': basket.product.stripe_product_price_id,
                'quantity': basket.quantity,
            }
            line_items.append(item)

        checkout_session = stripe.checkout.Session.create(
            line_items=line_items,
            metadata={'order_id': self.object.id},
            mode='payment',
            success_url=f"{settings.DOMAIN_NAME}{reverse('orders:order_success')}",
            cancel_url=f"{settings.DOMAIN_NAME}{reverse('orders:order_canceled')}",
        )
        return JsonResponse({
            "success": True,
            "redirect_url": checkout_session.url
        })

    def form_invalid(self, form):
        return JsonResponse({
            "success": False,
            "errors": form.errors
        }, status=400)


@csrf_exempt
def stripe_webhook_view(request):
    payload = request.body
    sig_header = request.META.get('HTTP_STRIPE_SIGNATURE', '')
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except (ValueError, stripe.error.SignatureVerificationError):
        return HttpResponse(status=400)

    if event['type'] in ['checkout.session.completed', 'checkout.session.async_payment_succeeded']:
        fulfill_checkout(event['data']['object'])  # Передаём объект, а не id

    return HttpResponse(status=200)


def fulfill_checkout(session):
    order_id = session.get('metadata', {}).get('order_id')  # Безопасное извлечение

    if not order_id:
        return  # Не нашли order_id, не можем обработать заказ

    try:
        order = Order.objects.get(id=int(order_id))
    except Order.DoesNotExist:
        return  # Заказ не найден

    order.update_after_payment()


orders/templates/orders/order-cancel.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Платёж не прошёл</title>

    <link rel="icon" type="image/x-icon" href="{% static 'favicon/favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'favicon/android-icon-192x192.png' %}">

    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
</head>

<body>

    {% include 'header.html' %}


    <section class="order-success">
        <div class="container">
            <div class="order-success__block">
                <div class="order-success__title-wrapper">
                    <h1 class="title title_center">Платёж не прошёл!</h1>
                </div>
                <div class="order-success__description">Произошла ошибка при оплате заказа!</div>
                
                <div class="order-success__btn-wrapper">
                    <a href="{% url 'products:basket' %}" class="order-success__btn">Перейти в корзину</a>
                </div>
            </div>
        </div>
    </section>


    {% include 'footer.html' %}


    {% include 'cookie.html' %}




    <script src="https://code.jquery.com/jquery-3.6.4.min.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-migrate-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.1/gsap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>


</body>

</html>

orders/templates/orders/order-success.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Спасибо за оформление заказа</title>

    <link rel="icon" type="image/x-icon" href="{% static 'favicon/favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'favicon/android-icon-192x192.png' %}">

    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
</head>

<body>

    {% include 'header.html' %}


    <section class="order-success">
        <div class="container">
            <div class="order-success__block">
                <div class="order-success__title-wrapper">
                    <h1 class="title title_center">Спасибо!</h1>
                </div>
                <div class="order-success__description">Ваш заказ успешно оформлен!</div>
                <div class="order-success__btn-wrapper">
                    <a href="{% url 'users:profile' %}" class="order-success__btn">Перейти в личный кабинет</a>
                </div>
            </div>
        </div>
    </section>


    {% include 'footer.html' %}


    {% include 'cookie.html' %}




    <script src="https://code.jquery.com/jquery-3.6.4.min.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-migrate-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.1/gsap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>


</body>

</html>

orders/templates/orders/order_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Детали заказа</title>

    <link rel="icon" type="image/x-icon" href="{% static 'favicon/favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'favicon/android-icon-192x192.png' %}">

    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
</head>

<body>

{% include 'header.html' %}


<section class="details-section">
    <div class="container">
        <div class="page-header__title-wrapper">
            <a href="{% url 'users:profile' %}" class="page-header__link-back-block">
                <img src="{% static 'icons/arrowBack.svg' %}" alt="Вернуться назад">
                <div class="page-header__link-back">Назад</div>
            </a>
            <div class="page-header__title-block">
                <h1 class="title">Подробности заказа №{{ order.id }}</h1>
            </div>
        </div>
        <div class="page-header__date">от {{ order.created_at|date:"d.m.Y" }}</div>

        <div class="details-section__table-block">
            <table class="details-section__table">
                <thead class="details-section__table-head">
                <tr class="details-section__table-row">
                    <th class="details-section__table-header">Название товара</th>
                    <th class="details-section__table-header">Количество</th>
                    <th class="details-section__table-header">Цена</th>
                    <th class="details-section__table-header">Сумма</th>
                </tr>
                </thead>
                <tbody class="details-section__table-body">
                {% for item in order.basket_history.purchased_items %}
                    <tr class="details-section__table-row">
                        <td class="details-section__table-data">{{ item.product_name }}</td>  <!-- Название товара -->
                        <td class="details-section__table-data">{{ item.quantity }}</td>  <!-- Количество -->
                        <td class="details-section__table-data">{{ item.price|floatformat:2 }} ₽</td>
                        <!-- Цена товара -->
                        <td class="details-section__table-data">{{ item.sum|floatformat:2 }} ₽</td>
                        <!-- Сумма товара -->
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="details-section__low-block-wrapper">
                <div class="details-section__status-sum-block">
                    <div class="details-section__status-sum">Статус: <span
                            class="details-section__status-sum-fw">{{ order.get_status_display }}</span></div>
                    <div class="details-section__status-sum">Итоговая сумма: <span
                            class="details-section__status-sum-fw">{{ order.basket_history.total_sum|floatformat:2 }} ₽</span>
                    </div>
                </div>
                {% if order.rejection_reason %}
                    <div class="details-section__rejection-block">
                        <div class="details-section__rejection-title">Причина отказа</div>
                        <textarea class="details-section__rejection-textarea"
                                  readonly>{{ order.rejection_reason }}</textarea>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>


{% include 'footer.html' %}


{% include 'cookie.html' %}


<script src="https://code.jquery.com/jquery-3.6.4.min.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-migrate-3.4.1.min.js" crossorigin="anonymous"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.1/gsap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js"></script>
<script src="{% static 'js/script.js' %}"></script>


</body>

</html>

orders/templates/orders/order_form.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Оформление заказа</title>

    <link rel="icon" type="image/x-icon" href="{% static 'favicon/favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'favicon/android-icon-192x192.png' %}">

    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
</head>

<body>

    {% include 'header.html' %}


    <section class="order-form">
        <div class="container">
            <h1 class="title title_center">Оформление заказа</h1>
            <div class="order-form__block">
                <form action="{% url 'orders:order_create' %}" method="post" class="order-form__form" novalidate>
                {% csrf_token %}
                    <div class="order-form__form-field-wrapper">
                        <div class="order-form__form-field">
                            <label for="{{ form.first_name.id_for_label }}" class="order-form__label">Имя</label>
                            {{ form.first_name }}
                            {% if form.first_name.errors %}
                                    <div class="text-danger">{{ form.first_name.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="order-form__form-field">
                            <label for="{{ form.last_name.id_for_label }}" class="order-form__label">Фамилия</label>
                            {{ form.last_name }}
                            {% if form.last_name.errors %}
                                    <div class="text-danger">{{ form.last_name.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="order-form__form-field">
                            <label for="{{ form.email.id_for_label }}" class="order-form__label">Адрес электронной почты</label>
                            {{ form.email }}
                            {% if form.email.errors %}
                                    <div class="text-danger">{{ form.email.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="order-form__form-field">
                            <label for="{{ form.phone_number.id_for_label }}" class="order-form__label">Номер телефона</label>
                            {{ form.phone_number }}
                            {% if form.phone_number.errors %}
                                    <div class="text-danger">{{ form.phone_number.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="order-form__form-field">
                            <label for="{{ form.address.id_for_label }}" class="order-form__label">Адрес доставки</label>
                            {{ form.address }}
                            {% if form.address.errors %}
                                    <div class="text-danger">{{ form.address.errors }}</div>
                            {% endif %}
                        </div>
                    </div>
                    <button type="submit" class="order-form__form-btn">Продолжить</button>
                </form>
            </div>
        </div>
    </section>


    {% include 'footer.html' %}


    {% include 'cookie.html' %}




    <script src="https://code.jquery.com/jquery-3.6.4.min.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-migrate-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.1/gsap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.9/jquery.inputmask.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>


</body>

</html>