YUPZ/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from orders.views import stripe_webhook_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('products/', include('products.urls', namespace='products')),
    path('vacancies/', include('vacancy.urls', namespace='vacancy')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                             document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import OrderCreateView, SuccessTemplateView, CanceledTemplateView, OrderDetailView

app_name = 'orders'

urlpatterns = [
    path('order/', OrderCreateView.as_view(), name='order_create'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order_list'),
    path('order-success/', SuccessTemplateView.as_view(), name='order_success'),
    path('order-canceled/', CanceledTemplateView.as_view(), name='order_canceled'),
]

users/urls.py
from django.urls import path
from .views import (LoginView, RegisterView, ProfileView, CustomLogoutView, CustomPasswordResetView,
                    CustomPasswordResetConfirmView)
from django.contrib.auth import views as auth_views


app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
    # другие маршруты
]

vacancy/urls.py
from django.urls import path
from .views import (VacancyListView, VacancyDetailView, filter_vacancies, RevokeApplicationView,
                    ApplicationDetailView)

app_name = 'vacancy'

urlpatterns = [
    path('', VacancyListView.as_view(), name='vacancy_list'),
    path('<int:pk>/', VacancyDetailView.as_view(), name='vacancy_detail'),
    path('filter/', filter_vacancies, name='filter_vacancies'),
    path('revoke_application/<int:pk>/', RevokeApplicationView.as_view(), name='revoke_application'),
    path('application/<int:pk>/', ApplicationDetailView.as_view(), name='application_details'),
]

orders/models.py
from django.db import models
from users.models import User
from products.models import Basket


class Order(models.Model):
    CREATED = 0
    CONFIRMED = 1
    PLANNING = 2
    IN_PRODUCTION = 3
    QUALITY_CONTROL = 4
    READY_FOR_SHIPMENT = 5
    SENT_TO_DELIVERY = 6
    DELIVERED = 7
    COMPLETED = 8
    CANCELLED = 9

    STATUS_CHOICES = [
        (CREATED, 'Новый'),
        (CONFIRMED, 'Подтверждён'),
        (PLANNING, 'В планировании'),
        (IN_PRODUCTION, 'В производстве'),
        (QUALITY_CONTROL, 'Контроль качества (ОТК)'),
        (READY_FOR_SHIPMENT, 'Готов к отгрузке'),
        (SENT_TO_DELIVERY, 'Передан в доставку'),
        (DELIVERED, 'Доставлен'),
        (COMPLETED, 'Завершён'),
        (CANCELLED, 'Отменён'),
    ]

    first_name = models.CharField(max_length=150, verbose_name='Имя')
    last_name = models.CharField(max_length=150, verbose_name='Фамилия')
    email = models.EmailField(max_length=256, verbose_name='Почта')
    phone_number = models.CharField(max_length=50, verbose_name='Номер телефона')
    address = models.CharField(max_length=256, verbose_name='Адрес доставки')
    basket_history = models.JSONField(default=dict, verbose_name='История корзины')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='Пользователь')
    rejection_reason = models.TextField(blank=True, null=True, verbose_name="Причина отказа")
    status = models.SmallIntegerField(default=CREATED, choices=STATUS_CHOICES, verbose_name='Статус')

    def __str__(self):
        return f'Заказ {self.id} {self.first_name} {self.last_name}'

    def update_after_payment(self):
        baskets = Basket.objects.filter(user=self.initiator)
        self.status = self.CONFIRMED
        self.basket_history = {
            'purchased_items': [basket.de_json() for basket in baskets],
            'total_sum': float(Basket.total_sum(self.initiator)),
        }
        baskets.delete()
        self.save()


users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    patronymic = models.CharField(max_length=30, blank=True, null=True, verbose_name="Отчество")
    phone_number = models.CharField(max_length=18, verbose_name="Номер телефона")




users/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserCreationForm, UserChangeForm, PasswordResetForm,
                                       SetPasswordForm)
from users.models import User
from django.core.exceptions import ValidationError
import re


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'login__input', 'placeholder': 'Введите ваш логин', 'autocomplete': 'username'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'login__input', 'placeholder': 'Введите ваш пароль', 'autocomplete': 'current-password'
    }))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'registration__input', 'placeholder': 'Введите ваше Имя'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'registration__input', 'placeholder': 'Введите вашу Фамилию'
    }))
    patronymic = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'registration__input', 'placeholder': 'Введите ваше Отчество'
    }), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'registration__input', 'placeholder': 'Введите ваш логин', 'autocomplete': 'username'
    }))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'registration__input', 'placeholder': 'Введите ваш номер'
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'registration__input', 'placeholder': 'Введите вашу Почту', 'autocomplete': 'email'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'registration__input', 'placeholder': 'Введите ваш Пароль', 'autocomplete': 'new-password'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'registration__input', 'placeholder': 'Подтвердите ваш Пароль', 'autocomplete': 'new-password'
    }))

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if not re.match(r'^[а-яА-ЯёЁ\s-]+$', first_name):
            raise ValidationError('Имя должно содержать только кириллицу, пробелы и тире.')
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
        if not re.match(r'^[а-яА-ЯёЁ\s-]+$', last_name):
            raise ValidationError('Фамилия должна содержать только кириллицу, пробелы и тире.')
        return last_name

    def clean_patronymic(self):
        patronymic = self.cleaned_data.get('patronymic')
        if patronymic and not re.match(r'^[а-яА-ЯёЁ\s-]+$', patronymic):
            raise ValidationError('Отчество должно содержать только кириллицу, пробелы и тире.')
        return patronymic

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Пользователь с такой почтой уже существует.')
        return email

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'patronymic', 'username', 'phone_number', 'email',
                  'password1', 'password2')


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'profile-content__form-input'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'profile-content__form-input'
    }))
    patronymic = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'profile-content__form-input'
    }), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'profile-content__form-input', 'readonly': True
    }))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'profile-content__form-input'
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'profile-content__form-input', 'autocomplete': 'email', 'readonly': True
    }))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'patronymic', 'username', 'phone_number', 'email')


class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={
            'class': 'forgot-password__input',
            'placeholder': 'Введите ваш email',
            'autocomplete': 'email'
        })
    )


class CustomSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'forgot-password__input',
            'placeholder': 'Новый пароль',
            'autocomplete': 'new-password'
        })
    )
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'forgot-password__input',
            'placeholder': 'Подтвердите пароль',
            'autocomplete': 'new-password'
        })
    )

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import FormView, CreateView, UpdateView, View
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth import views as auth_views
from .forms import (UserLoginForm, UserRegisterForm, UserProfileForm, CustomPasswordResetForm,
                    CustomSetPasswordForm)
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from vacancy.models import VacancyApplication
from django.contrib.auth import logout
from django.contrib import messages
from django.http import JsonResponse
from orders.models import Order

class LoginView(FormView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    success_url = reverse_lazy('users:profile')

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user:
            auth_login(self.request, user)
            messages.success(self.request, 'Вы успешно вошли в систему!')

            if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({"success": True})

            return super().form_valid(form)
        else:
            # Добавляем ошибку в форму
            form.add_error(None, "Неверный логин или пароль")
            return self.form_invalid(form)

    def form_invalid(self, form):
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            errors = {field: [error for error in error_list] for field, error_list in form.errors.items()}
            if form.non_field_errors():
                errors["password"] = form.non_field_errors()
            return JsonResponse({"success": False, "errors": errors})
        return super().form_invalid(form)


class RegisterView(CreateView):
    form_class = UserRegisterForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        messages.success(self.request, 'Вы успешно зарегистрировались!')

        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({"success": True})

        return super().form_valid(form)

    def form_invalid(self, form):
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({"success": False, "errors": form.errors}, status=400)

        return super().form_invalid(form)


class ProfileView(LoginRequiredMixin, UpdateView):
    form_class = UserProfileForm  # Форма для редактирования
    template_name = 'users/profile.html'  # Шаблон для отображения
    success_url = reverse_lazy('users:profile')  # URL для перенаправления после успешного редактирования

    def get_object(self, queryset=None):
        # Возвращаем текущего авторизованного пользователя
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        context['user'] = user

        context['orders'] = Order.objects.filter(initiator=user).order_by('-created_at')

        for order in context['orders']:
            order.status_display = order.get_status_display()

        context['applications'] = VacancyApplication.objects.filter(user=user)

        return context

    def form_valid(self, form):
        form.save()
        # Возвращаем JSON-ответ для AJAX
        return JsonResponse({
            'success': True,
            'message': 'Данные успешно обновлены!',
        })

    def form_invalid(self, form):
        # Возвращаем JSON-ответ с ошибками
        return JsonResponse({
            'success': False,
            'errors': form.errors,
        }, status=400)


class CustomLogoutView(View):
    @method_decorator(csrf_protect)
    def post(self, request, *args, **kwargs):
        # Выход из системы
        logout(request)
        messages.success(request, 'Вы успешно вышли из системы!')
        return redirect('main:home')


class CustomPasswordResetView(auth_views.PasswordResetView):
    form_class = CustomPasswordResetForm
    template_name = 'users/password_reset_form.html'
    email_template_name = 'users/password_reset_email.html'
    subject_template_name = 'users/password_reset_subject.txt'
    success_url = '/users/password_reset/done/'

    def form_valid(self, form):
        response = super().form_valid(form)

        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({"success": True})

        return response

    def form_invalid(self, form):
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({"success": False, "errors": form.errors}, status=400)

        return super().form_invalid(form)


class CustomPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    form_class = CustomSetPasswordForm  # Используем кастомную форму
    template_name = 'users/password_reset_confirm.html'  # Ваш шаблон
    success_url = '/users/reset/done/'  # URL после успешного сброса

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['uidb64'] = self.kwargs.get('uidb64')
        context['token'] = self.kwargs.get('token')
        return context

    def form_valid(self, form):
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            super().form_valid(form)  # Выполняем стандартную обработку
            return JsonResponse({"success": True})

        return super().form_valid(form)

    def form_invalid(self, form):
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({"success": False, "errors": form.errors}, status=400)

        return super().form_invalid(form)



users/templates/users/password_reset_form.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Запрос на восстановление пароля</title>

    <link rel="icon" type="image/x-icon" href="{% static 'favicon/favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'favicon/android-icon-192x192.png' %}">

    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
</head>

<body>

{% include 'header.html' %}


<section class="forgot-password">
    <div class="container">
        <div class="page-header__title-wrapper">
            <a href="{% url 'users:login' %}" class="page-header__link-back-block">
                <img src="{% static 'icons/arrowBack.svg' %}" alt="Вернуться назад">
                <div class="page-header__link-back">Назад</div>
            </a>
            <div class="page-header__title-block">
                <h1 class="title">Сброс пароля</h1>
            </div>
        </div>

        <div class="forgot-password__block">
            <div class="forgot-password__prompt">* Введите почту, на которую придет ссылка для сброса пароля</div>
            <form action="{% url 'users:password_reset' %}" method="post" class="forgot-password__form" data-success-url="{% url 'users:password_reset_done' %}" novalidate>
                {% csrf_token %}
                <div class="forgot-password__form-group">
                    <label for="{{ form.email.id_for_label }}" class="forgot-password__label">Почта</label>
                    {{ form.email }}
                    {% if form.email.errors %}
                        <div class="text-danger">{{ form.email.errors|join:"<br>" }}</div>
                    {% endif %}
                </div>
                <button type="submit" class="forgot-password__btn-submit">Сбросить пароль</button>
            </form>
        </div>

    </div>
</section>


{% include 'footer.html' %}


{% include 'cookie.html' %}

<script src="https://code.jquery.com/jquery-3.6.4.min.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-migrate-3.4.1.min.js" crossorigin="anonymous"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.1/gsap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js"></script>
<script src="{% static 'js/script.js' %}"></script>


</body>

</html>

users/templates/users/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Личный кабинет</title>

    <link rel="icon" type="image/x-icon" href="{% static 'favicon/favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'favicon/android-icon-192x192.png' %}">

    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
</head>

<body>

{% include 'header.html' %}


<div class="main_bg">
    <section class="profile">
        <div class="container">
            <h1 class="title title_center">Личный кабинет</h1>
            <div class="profile__tabs-wrapper">
                <ul class="profile__tabs-menu">
                    <li class="profile__tabs-item profile__tabs-item_active" data-tab="profile">Главная</li>
                    <li class="profile__tabs-item" data-tab="orders">История заказов</li>
                    <li class="profile__tabs-item" data-tab="vacancies">История вакансий</li>
                </ul>
            </div>
        </div>
    </section>

    <section class="profile-content">
        <div class="container">
            <div class="profile-content__wrapper">
                <div class="profile-content__content-item profile-content__content-item_active"
                     data-content="profile">
                    <div class="profile-content__form-block">
                        <div class="profile-content__form-flex">
                            <h2 class="profile-content__title">Личные данные</h2>
                            <form action="{% url 'users:profile' %}" method="post" class="profile-content__form"
                                  id="profile-form">
                                {% csrf_token %}
                                <div class="profile-content__form-field">
                                    <label for="{{ form.first_name.id_for_label }}" class="profile-content__form-label">Имя</label>
                                    {{ form.first_name }}
                                </div>
                                <div class="profile-content__form-field">
                                    <label for="{{ form.last_name.id_for_label }}"
                                           class="profile-content__form-label">Фамилия</label>
                                    {{ form.last_name }}
                                </div>
                                <div class="profile-content__form-field">
                                    <label for="{{ form.patronymic.id_for_label }}"
                                           class="profile-content__form-label">Отчество</label>
                                    {{ form.patronymic }}
                                </div>
                                <div class="profile-content__form-field">
                                    <label for="{{ form.username.id_for_label }}"
                                           class="profile-content__form-label">Логин</label>
                                    {{ form.username }}
                                </div>
                                <div class="profile-content__form-field">
                                    <label for="{{ form.phone_number.id_for_label }}"
                                           class="profile-content__form-label">Номер
                                        телефона</label>
                                    {{ form.phone_number }}
                                </div>
                                <div class="profile-content__form-field">
                                    <label for="{{ form.email.id_for_label }}"
                                           class="profile-content__form-label">Почта</label>
                                    {{ form.email }}
                                </div>
                                <button type="submit" class="profile-content__form-button-edit">
                                    Редактировать личные данные
                                    <img src="{% static 'icons/profileEdit.svg' %}" alt="Редактировать профиль">
                                </button>
                            </form>
                        </div>
                        <form action="{% url 'users:logout' %}" method="post" class="profile-content__form">
                            {% csrf_token %}
                            <button type="submit" class="profile-content__form-button-logout">
                                Выйти из аккаунта
                                <img src="{% static 'icons/profileLogout.svg' %}" alt="Выход из аккаунта">
                            </button>
                        </form>
                    </div>
                </div>
                <div class="profile-content__content-item" data-content="orders">
                    <h2 class="profile-content__title">Заказы</h2>
                    <div class="profile-content__block-wrapper">
                        {% for order in orders %}
                            <div class="profile-content__block">
                                <table class="profile-content__table">
                                    <thead class="profile-content__table-thead">
                                    <tr class="profile-content__table-tr">
                                        <th class="profile-content__table-th"><span>Заказ #{{ order.id }}</span></th>
                                        <th class="profile-content__table-th profile-content__table-th_center">Дата
                                            заказа
                                        </th>
                                        <th class="profile-content__table-th profile-content__table-th_center">Кол-во
                                            товаров
                                        </th>
                                        <th class="profile-content__table-th profile-content__table-th_center">Сумма
                                            заказа
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody class="profile-content__table-tbody">
                                    <tr class="profile-content__table-tr">
                                        <td class="profile-content__table-td">
                                            <span>Статус: {{ order.status_display }}</span></td>
                                        <td class="profile-content__table-td profile-content__table-td_center">{{ order.created_at|date:"d.m.Y" }}
                                        </td>
                                        <td class="profile-content__table-td profile-content__table-td_center">{{ order.basket_history.purchased_items|length }}</td>
                                        <td class="profile-content__table-td profile-content__table-td_center">{{ order.basket_history.total_sum }}
                                            ₽
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                                <div class="profile-content__table-btns-wrapper">
                                    <a href="{% url 'orders:order_list' order.pk %}" class="profile-content__table-btn">Подробности</a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="profile-content__content-item" data-content="vacancies">
                    <h2 class="profile-content__title">Заявка на вакансии</h2>
                    <div class="profile-content__block-wrapper">
                        {% for application in applications %}
                            <div class="profile-content__block">
                                <table class="profile-content__table">
                                    <thead class="profile-content__table-thead">
                                    <tr class="profile-content__table-tr">
                                        <th class="profile-content__table-th"><span>Заявка #{{ application.id }}</span>
                                        </th>
                                        <th class="profile-content__table-th profile-content__table-th_center">Дата
                                            подачи заявки
                                        </th>
                                        <th class="profile-content__table-th profile-content__table-th_center">
                                            Должность
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody class="profile-content__table-tbody">
                                    <tr class="profile-content__table-tr">
                                        <td class="profile-content__table-td">
                                            <span>Статус: {{ application.get_status_display }}</span></td>
                                        <td class="profile-content__table-td profile-content__table-td_center">{{ application.created_at|date:"d.m.Y" }}</td>
                                        <td class="profile-content__table-td profile-content__table-td_center">{{ application.vacancy.title }}</td>
                                    </tr>
                                    </tbody>
                                </table>
                                <div class="profile-content__table-btns-wrapper">
                                    {% if application.status == 'created' %}
                                        <a href="#"
                                           class="profile-content__table-btn revoke-btn" data-id="{{ application.id }}">Отозвать</a>
                                    {% endif %}
                                    <a href="{% url 'vacancy:application_details' application.pk %}"
                                       class="profile-content__table-btn">Подробности</a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>


{% include 'footer.html' %}

{% include 'notification.html' %}

<div class="notification" id="notification">
    <div class="notification__text"></div>
</div>


{% include 'cookie.html' %}


<script src="https://code.jquery.com/jquery-3.6.4.min.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-migrate-3.4.1.min.js" crossorigin="anonymous"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.1/gsap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js"></script>
<script src="{% static 'js/script.js' %}"></script>


</body>

</html>